DROP TABLE PQAMCLUM.PQAMC_DATA_UPLOAD CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_DATA_UPLOAD
(
  AMC_NAME                VARCHAR2(500 BYTE),
  FUND_NAME               VARCHAR2(200 BYTE),
  TRANSACTION_TYPE        VARCHAR2(100 BYTE),
  DATA_TYPE               VARCHAR2(100 BYTE),
  TRANSACTION_ID          VARCHAR2(100 BYTE),
  NAV_APPLICABLE_DATE     DATE,
  APPLICABLE_NAV          NUMBER,
  PROCESS_DATE            DATE,
  AGENT_NAME              VARCHAR2(100 BYTE),
  CHANNEL                 VARCHAR2(20 BYTE),
  FOLIO_NO                VARCHAR2(20 BYTE),
  UNIT_HOLDER_TITLE       VARCHAR2(100 BYTE),
  STAMPING_FIELD          VARCHAR2(50 BYTE),
  CONTROL_FIELD           VARCHAR2(50 BYTE),
  GROSS_AMOUNT            NUMBER,
  LOAD                    NUMBER,
  REBATE                  NUMBER,
  CGT                     NUMBER,
  ZAKAT                   NUMBER,
  TRANSACTION_CHARGES     NUMBER,
  OTHER_CHARGES           NUMBER,
  CERTIFICATE_CHARGES     NUMBER,
  NET_AMOUNT              NUMBER,
  UNIT_REALIZED           NUMBER,
  UNIT_REVERSED_ADJUSTED  NUMBER,
  REGION                  VARCHAR2(100 BYTE),
  TYPE_CUSTOMER           VARCHAR2(50 BYTE),
  GROUPING                VARCHAR2(50 BYTE),
  AGENT_CODE              VARCHAR2(50 BYTE),
  CANCEL_YN               CHAR(1 BYTE)          DEFAULT 'N'
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_DAY_END CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_DAY_END
(
  DAY_END_ID_PK  NUMBER,
  DAY_END_DATE   DATE,
  ENTER_DATE     DATE,
  USER_ID_FK     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_DIVIDEND_PROCESS_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_DIVIDEND_PROCESS_DETAIL
(
  PROCESS_DETAIL_PK  NUMBER,
  PROCESS_ID_FK      NUMBER,
  PARTICIPANT_ID_FK  NUMBER,
  CLSOING_UNIT       NUMBER,
  DIVIDEND_RATE      NUMBER,
  DIVIDEND_DATE      DATE,
  DIVIDEND_AMOUNT    NUMBER,
  FILER_STATUS       CHAR(1 BYTE),
  TAX_PCT            NUMBER,
  TAX_AMOUNT         NUMBER,
  NET_AMOUNT         NUMBER,
  NAV_DATE           DATE,
  NAV_RATE           NUMBER,
  ENTER_DATE         DATE,
  USER_ID_FK         NUMBER,
  UNITS              NUMBER,
  LAST_UPDATED_DATE  DATE,
  LAST_UPDATED_BY    NUMBER,
  FT_DONE            CHAR(1 BYTE)               DEFAULT 'N',
  INVOICE_CODE       CHAR(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_DIVIDEND_PROCESS_MASTER CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_DIVIDEND_PROCESS_MASTER
(
  PROCESS_ID_PK       NUMBER,
  PROCESS_DATE        DATE,
  UNITS_CLOSING_DATE  DATE,
  USER_ID_FK          NUMBER,
  ENTER_DATE          DATE,
  APPROVE_USER_ID_FK  NUMBER,
  APPROVE_DATE        DATE,
  FUND_TYPE_ID_FK     NUMBER,
  DIVIDEND_RATE       NUMBER,
  DIVIDEND_DATE       DATE,
  LAST_UPDATED_DATE   DATE,
  LAST_UPDATED_BY     NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_FIFO_TRACK CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_FIFO_TRACK
(
  TRACK_ID           NUMBER,
  PARTICIPANT_ID_FK  NUMBER,
  BUY_TRNS_DTL_ID    NUMBER,
  SELL_TRNS_DTL_ID   NUMBER,
  UNIT_OUT           NUMBER,
  BUY_RATE           NUMBER,
  SELL_RATE          NUMBER,
  RATE_DIFF          NUMBER,
  GAIN_AMOUNT        NUMBER,
  CGT_RATE           NUMBER,
  CGT_AMOUNT         NUMBER,
  ENTER_DATE         DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_FINANCE_TABLES CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_FINANCE_TABLES
(
  S_NO              NUMBER,
  T_DATE            DATE,
  ACCOUNT_CODE_NEW  VARCHAR2(50 BYTE),
  NARRATION         VARCHAR2(100 BYTE),
  REF_NO            NUMBER,
  DOC_TYPE          CHAR(2 BYTE),
  DEBIT_AMOUNT      NUMBER,
  CREDIT_AMOUNT     NUMBER,
  VOUCHER_NO        VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_FOLIO_TRANSFER_LOG CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_FOLIO_TRANSFER_LOG
(
  FOLIO_TRANSFER_ID_PK    NUMBER,
  FROM_PARTICIPANT_ID_FK  NUMBER                NOT NULL,
  TO_PARTICIPANT_ID_FK    NUMBER                NOT NULL,
  USER_ID_FK              NUMBER                NOT NULL,
  ENTER_DATE              DATE                  NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_FOLIO_TRANSFER_LOG_DTL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_FOLIO_TRANSFER_LOG_DTL
(
  FOLIO_TRANSFER_DTL_ID_PK  NUMBER              NOT NULL,
  FOLIO_TRANSFER_ID_FK      NUMBER              NOT NULL,
  FUND_ID_FK                NUMBER              NOT NULL,
  UNIT_TRANSFFERED          NUMBER              NOT NULL,
  AMOUNT_TRANSFFERED        NUMBER              NOT NULL,
  USER_ID_FK                NUMBER              NOT NULL,
  ENTER_DATE                DATE                NOT NULL,
  TRANSACTION_ID_FK         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_BENEFICIARY CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_BENEFICIARY
(
  BENEFICIARY_ID_PK  NUMBER,
  PARTICIPANT_ID_FK  NUMBER,
  BENEFICIARY_NAME   VARCHAR2(200 BYTE),
  BEN_REL_ID_FK      NUMBER,
  BEN_CNIC           VARCHAR2(30 BYTE),
  ENTER_DATE         DATE,
  USER_ID_FK         NUMBER,
  BEN_CONTRACT_NO    VARCHAR2(100 BYTE),
  BEN_EMAIL          VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_DIRECTORS CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_DIRECTORS
(
  DIRECTOR_ID_PK              NUMBER,
  PARTICIPANT_ID_FK           NUMBER,
  DIRECTOR_NAME               VARCHAR2(200 BYTE),
  DIRECTOR_DESIGNATION_ID_FK  NUMBER,
  DIRECTOR_CNIC               VARCHAR2(30 BYTE),
  ENTER_DATE                  DATE,
  USER_ID_FK                  NUMBER,
  DIRECTOR_CONTACT_NO         VARCHAR2(100 BYTE),
  DIRECTOR_EMAIL              VARCHAR2(100 BYTE),
  TITLE_ID                    VARCHAR2(100 BYTE),
  CNIC_EXPIRY_DATE            DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_DIVIDEND_TAX CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_DIVIDEND_TAX
(
  PARTICIPANT_ID_FK   NUMBER,
  S_NO                NUMBER,
  START_DATE          DATE,
  END_DATE            DATE,
  CREATED_DATE        DATE,
  CREATED_BY          NUMBER,
  EXEMPT_Y_N          CHAR(1 BYTE)              DEFAULT 'N',
  DOC_ID_PK           NUMBER,
  DOC_TYPE_FILE_NAME  VARCHAR2(50 BYTE),
  DOCUMENTS           BLOB,
  ENTER_DATE          DATE,
  USER_ID_FK          NUMBER
)
LOB (DOCUMENTS) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_DOCUMENTS CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_DOCUMENTS
(
  DOC_ID_PK           NUMBER,
  DOC_TYPE_ID_FK      NUMBER,
  DOC_TYPE_FILE_NAME  VARCHAR2(50 BYTE),
  DOCUMENTS           BLOB,
  ENTER_DATE          DATE,
  USER_ID_FK          NUMBER,
  PARTICIPANT_ID_FK   NUMBER,
  RECEIVED_STATUS     CHAR(1 BYTE)
)
LOB (DOCUMENTS) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING
      STORAGE    (
                  INITIAL          104K
                  NEXT             1M
                  MINEXTENTS       1
                  MAXEXTENTS       UNLIMITED
                  PCTINCREASE      0
                  BUFFER_POOL      DEFAULT
                 ))
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_GUARDIAN CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_GUARDIAN
(
  GUARDIAN_ID_PK        NUMBER                  NOT NULL,
  PARTICIPANT_ID_FK     NUMBER,
  GUARDIAN_NAME         VARCHAR2(200 BYTE),
  GUARDIAN_REL_ID_FK    NUMBER,
  GUARDIAN_CNIC         VARCHAR2(30 BYTE),
  GUARDIAN_CNIC_EXPIRY  DATE,
  ENTER_DATE            DATE,
  USER_ID_FK            NUMBER,
  ZAKAT                 VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_JOINT_AC CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_JOINT_AC
(
  JOINT_ID_PK          NUMBER                   NOT NULL,
  PARTICIPANT_ID_FK    NUMBER,
  JOINT_NAME           VARCHAR2(200 BYTE),
  JOINT_REL_ID_FK      NUMBER,
  JOINT_CNIC           VARCHAR2(30 BYTE),
  JOINT_CNIC_ISSUANCE  DATE,
  JOINT_CNIC_EXPIRY    DATE,
  ENTER_DATE           DATE,
  USER_ID_FK           NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_NEXT_KIN CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_NEXT_KIN
(
  KIN_ID_PK          NUMBER                     NOT NULL,
  PARTICIPANT_ID_FK  NUMBER,
  KIN_NAME           VARCHAR2(200 BYTE),
  KIN_REL_ID_FK      NUMBER,
  KIN_CNIC           VARCHAR2(30 BYTE),
  KIN_CONTRACT_NO    VARCHAR2(100 BYTE),
  KIN_ADDRESS        VARCHAR2(200 BYTE),
  ENTER_DATE         DATE,
  USER_ID_FK         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_SIGNATORY CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_SIGNATORY
(
  SIGNATORY_ID_PK              NUMBER,
  PARTICIPANT_ID_FK            NUMBER,
  SIGNATORY_NAME               VARCHAR2(200 BYTE),
  SIGNATORY_DESIGNATION_ID_FK  NUMBER,
  SIGNATORY_CNIC               VARCHAR2(30 BYTE),
  ENTER_DATE                   DATE,
  USER_ID_FK                   NUMBER,
  SIGNATORY_CONTRACT_NO        VARCHAR2(100 BYTE),
  SIGNATORY_EMAIL              VARCHAR2(100 BYTE),
  TITLE_ID                     VARCHAR2(100 BYTE),
  CNIC_EXPIRY_DATE             DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_TAX_DTL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_TAX_DTL
(
  TAX_MST_FK             NUMBER,
  S_NO                   NUMBER,
  START_DATE             DATE,
  END_DATE               DATE,
  CREATED_DATE           DATE,
  CREATED_BY             NUMBER,
  FROM_PERIOD            DATE,
  TO_DATE                DATE,
  DOCUMENTS              BLOB,
  FILE_NAME_DESCRIPTION  VARCHAR2(200 BYTE),
  DOCUMENT_ID_PK         NUMBER
)
LOB (DOCUMENTS) STORE AS SECUREFILE (
  TABLESPACE  USERS
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  NOCACHE
  LOGGING)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_PART_TAX_MST CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_PART_TAX_MST
(
  TAX_MST_ID         NUMBER,
  PARTICIPANT_ID_FK  NUMBER,
  SETUP_DTL_ID_FK    NUMBER,
  CREATED_DATE       DATE,
  CREATED_BY         NUMBER,
  EXEMPT_Y_N         CHAR(1 BYTE)               DEFAULT 'N'
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_CGT_TAX CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_CGT_TAX
(
  CGT_TAX_ID_PK   NUMBER,
  CGT_CATEGORY    CHAR(1 BYTE),
  CGT_ATL_STATUS  CHAR(1 BYTE),
  CGT_TAX_RATE    NUMBER,
  CGT_EFFT_FM     DATE,
  CGT_EFFT_TO     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_CGT_TAX.CGT_CATEGORY IS 'I=Individual,C=Corporate';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_CGT_TAX.CGT_ATL_STATUS IS 'F=File, N=Non-Filer,E=Exempt';


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_CHARGES_TAX CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_CHARGES_TAX
(
  CHAGES_ID_PK     NUMBER,
  FUND_TYPE_ID_FK  NUMBER,
  FE_LOAD          NUMBER,
  BE_LOAD          NUMBER,
  SST_TAX          NUMBER,
  EFFECTIVE_DT     DATE,
  ENTER_DATE       DATE,
  USER_ID_FK       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_FUND CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_FUND
(
  FUND_ID_PK       NUMBER,
  FUND_NAME        VARCHAR2(100 BYTE),
  FUND_SHORT_NAME  VARCHAR2(10 BYTE),
  ENTER_DATE       DATE,
  USER_ID_FK       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE
(
  FUND_TYPE_ID_PK       NUMBER,
  FUND_TYPE_NAME        VARCHAR2(100 BYTE),
  FUND_TYPE_SHORT_NAME  VARCHAR2(10 BYTE),
  ENTER_DATE            DATE,
  USER_ID_FK            NUMBER,
  PROCEN_ID_FK          NUMBER,
  DIVIDEND              VARCHAR2(1 BYTE),
  MUFAP_FUND_NAME       VARCHAR2(200 BYTE),
  IMC_PCT               NUMBER,
  ITMINDS_FUND_MAP      VARCHAR2(100 BYTE),
  FROM_DATE             DATE,
  TO_DATE               DATE,
  PRICING_METHOD        VARCHAR2(1 BYTE),
  FUND_ID_FK            NUMBER,
  REALIZATION           CHAR(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE.PROCEN_ID_FK IS 'Epf_Gen_St_Profitcenter';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE.MUFAP_FUND_NAME IS 'Purpose link between investment system  to unit management system for NAV';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE.ITMINDS_FUND_MAP IS 'Purpose link between ITMINDS system  to unit management system';


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE_DTL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE_DTL
(
  FUND_DTL_ID_PK   NUMBER,
  FUND_TYPE_ID_FK  NUMBER,
  UNIT_TYPE_ID_FK  NUMBER,
  ENTER_DATE       DATE,
  USER_ID_FK       NUMBER,
  DEFAULT_TYPE     CHAR(1 BYTE),
  EFFECTIVE_DT     DATE,
  FM_AMOUNT        NUMBER,
  TO_AMOUNT        NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_HOLIDAYS CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_HOLIDAYS
(
  HOLIDAY_ID_PK    NUMBER,
  HOLIDAY_DESC     VARCHAR2(100 BYTE),
  HOLIDAY_FM_DATE  DATE,
  HOLIDAY_TO_DATE  DATE,
  USER_ID_FK       NUMBER,
  ENTER_DATE       DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_IMC_RATE CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_IMC_RATE
(
  RATE_ID_PK       NUMBER                       NOT NULL,
  FUND_TYPE_ID_FK  NUMBER                       NOT NULL,
  EFF_FROM_DT      DATE                         NOT NULL,
  EFF_TO_DT        DATE                         NOT NULL,
  USER_ID_FK       NUMBER                       NOT NULL,
  ENTER_DATE       DATE                         NOT NULL,
  IMC_PCT          NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_MANAGEMENT_CHARGE CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_MANAGEMENT_CHARGE
(
  MANAGEMENT_ID_PK           NUMBER,
  FUND_TYPE_ID_FK            NUMBER,
  MANAGEMENT_CHARGE_AMOUNT   NUMBER(10),
  MANAGEMENT_CHARGE_PERCENT  NUMBER(5),
  EFFECTIVE_DT               DATE,
  INEFFECTIVE_DT             DATE,
  ENTER_DATE                 DATE,
  USER_ID_FK                 NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT
(
  PARTICIPANT_ID_PK           NUMBER            NOT NULL,
  PARTICIPANT_NAME            VARCHAR2(500 BYTE),
  ACTIVE                      VARCHAR2(1 BYTE)  DEFAULT 'N',
  PHONE                       VARCHAR2(100 BYTE),
  FAX                         VARCHAR2(100 BYTE),
  MOBILE                      VARCHAR2(100 BYTE),
  EMAIL                       VARCHAR2(500 BYTE),
  OCCUPATION_ID_FK            NUMBER,
  TAX_EXEMPT_NO               VARCHAR2(100 BYTE),
  REGISTRATION_NO             VARCHAR2(100 BYTE),
  ZIP_CODE                    VARCHAR2(10 BYTE),
  PO_BOX_NO                   VARCHAR2(10 BYTE),
  NTN_NO                      VARCHAR2(100 BYTE),
  NIC                         VARCHAR2(60 BYTE),
  NIC_ISSUE_DATE              DATE,
  NIC_EXPIRE_DATE             DATE,
  ATL_STATUS                  VARCHAR2(1 BYTE)  DEFAULT 'N',
  BLACK_LIST                  VARCHAR2(1 BYTE)  DEFAULT 'N',
  REMARKS                     VARCHAR2(200 BYTE),
  USER_ID_FK                  NUMBER            NOT NULL,
  ENTER_DATE                  DATE              NOT NULL,
  SHORT_NAME                  VARCHAR2(20 BYTE),
  PARENT_PARTICIPANT_ID       NUMBER,
  GENDER                      CHAR(1 BYTE),
  BANK_BR_ID_FK               NUMBER,
  BANK_ID_FK                  NUMBER,
  IBAN_NO                     VARCHAR2(50 BYTE),
  ACC_NO                      VARCHAR2(100 BYTE),
  ZAKAT_DEDUCTION             CHAR(1 BYTE),
  FILER_STATUS                CHAR(1 BYTE),
  RESIDENTIAL_STATUS          NUMBER,
  DOP                         NUMBER,
  DOB                         DATE,
  DUAL_NATIONALITY            CHAR(1 BYTE),
  NATIONALITY                 NUMBER,
  RELIGION                    NUMBER,
  MARITAL_STATUS              NUMBER,
  MOTHER_NAME                 VARCHAR2(500 BYTE),
  FATHER_HUSBAND_NAME         VARCHAR2(500 BYTE),
  TITLE_ID                    NUMBER,
  ACCOUNT_TYPE                CHAR(1 BYTE),
  PARTICIPANT_TYPE            CHAR(1 BYTE),
  COUNTRY_CODE                VARCHAR2(50 BYTE),
  COMPANYID_FK                NUMBER,
  CASH_DIVIDEND               CHAR(1 BYTE),
  STOCK_DIVIDEND              CHAR(1 BYTE),
  ACCOUNT_OPERATE_INST        CHAR(1 BYTE),
  SOURCE_INCOME_ID            NUMBER,
  SOURCE_WEALTH_ID            NUMBER,
  NAME_EMPLOY_BUSINESS        VARCHAR2(100 BYTE),
  DESIGNATION_ID              NUMBER,
  EDUCATION_ID                NUMBER,
  ANNUAL_INCOME_ID            NUMBER,
  CONTACT_PERSON_NAME         VARCHAR2(200 BYTE),
  CONTACT_PERSON_EMAIL        VARCHAR2(100 BYTE),
  CONTACT_PERSON_PHONE        VARCHAR2(100 BYTE),
  CONTACT_PERSON_MOBILE       VARCHAR2(100 BYTE),
  GEO_DOMESTIC                NUMBER,
  GEO_INTERNATIONAL           CHAR(1 BYTE),
  TYPE_COUNTER_DOMESTIC       NUMBER,
  TYPE_COUNTER_INTERNATIONAL  CHAR(1 BYTE),
  CHANNEL_ID_FK               NUMBER,
  ITMINDS_FOLIO_NO            NUMBER,
  ZAKAT_YN                    CHAR(1 BYTE)      DEFAULT 'N',
  ITMINDS_DATA_IDENTIFIER     VARCHAR2(10 BYTE),
  COUNTRY_ID_FK               NUMBER,
  CITY_ID_FK                  NUMBER,
  PROVINCE_ID_FK              NUMBER,
  PASSPORT_NO                 VARCHAR2(50 BYTE),
  PASSPORT_ISSUE_DATE         DATE,
  PASSPORT_EXPIRY_DATE        DATE,
  ALTERATION_ID_FK            NUMBER,
  AGE                         NUMBER,
  SUM_COVERED                 NUMBER,
  VERIFY_ACCOUNT_TITLE        VARCHAR2(550 BYTE),
  IBAN_VERIFY_FLAG            VARCHAR2(1 BYTE)  DEFAULT 'N',
  ADDRESS                     VARCHAR2(500 BYTE),
  ADDRESS_2                   VARCHAR2(500 BYTE),
  ADDRESS_3                   VARCHAR2(500 BYTE),
  MOTHER_CNIC                 VARCHAR2(60 BYTE),
  FATHER_CNIC                 VARCHAR2(60 BYTE),
  ZAKAT_DECLARATION           VARCHAR2(1 BYTE)  DEFAULT 'N',
  SMOKER_FLAG                 VARCHAR2(1 BYTE)  DEFAULT 'N',
  UW_APPROVED_DATE            DATE,
  UW_STATUS_ID_FK             NUMBER,
  CONTRIBUTION                NUMBER,
  SUBSIDIARY_COMPANY          VARCHAR2(100 BYTE),
  EPMD                        CHAR(1 BYTE),
  STOP_EPMD                   CHAR(1 BYTE),
  PROFIT_TYPE                 NUMBER,
  PROFIT_FIXED_AMT            NUMBER,
  ALTERATION_FLAG             CHAR(1 BYTE)      DEFAULT 'N',
  IBAN_MANUAL_VERIFY_FLAG     CHAR(1 BYTE)      DEFAULT 'N',
  ZAKAT_DECLARATION_MANUAL    CHAR(1 BYTE)      DEFAULT 'N',
  CGT                         CHAR(1 BYTE),
  WHT                         CHAR(1 BYTE),
  TRANSFERRED_FOLIO           CHAR(1 BYTE)      DEFAULT 'N',
  REGION_ID_FK                NUMBER,
  DISTRICT_ID_FK              NUMBER,
  ZONE_ID_FK                  NUMBER,
  URL                         VARCHAR2(500 BYTE),
  MIGRATION_YN                CHAR(1 BYTE),
  PERMANET_ADDRESS            VARCHAR2(4000 BYTE),
  LIFE_COVERAGE               VARCHAR2(50 BYTE),
  CUSTOMER_PORTAL_ID          NUMBER,
  SOURCE_TYPE_NAME            VARCHAR2(20 BYTE),
  CONVERSION_CUSTOMER         NUMBER,
  RESIDENT_COUNTRY_ID_FK      NUMBER,
  AGENT_ID_FK                 NUMBER,
  SHARE_COMM_PCT              NUMBER,
  PORTAL_ACCESS               VARCHAR2(2 BYTE)  DEFAULT 'Y',
  CP_OCC_ID_FK                NUMBER,
  GH_DOC_NO                   VARCHAR2(30 BYTE),
  CROSS_ADDRESS_TYPE          CHAR(1 BYTE),
  CGT_TAX                     CHAR(1 BYTE)      DEFAULT 'Y',
  DIVIDEND_TAX                CHAR(1 BYTE)      DEFAULT 'Y',
  RISK_CATEGORY               CHAR(1 BYTE)      DEFAULT 'L'
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT.ATL_STATUS IS 'ACTIVE TAX PAYER LIST, Y=ACTIVE, N=NON-ACTIVE';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT.GEO_DOMESTIC IS 'epf_gen_st_province';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT.GEO_INTERNATIONAL IS 'C=FATF Compliant,N=FATF Non-Compliant';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT.TYPE_COUNTER_DOMESTIC IS 'epf_gen_st_province';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT.TYPE_COUNTER_INTERNATIONAL IS 'C=FATF Compliant,N=FATF Non-Compliant';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT.CHANNEL_ID_FK IS 'EPF_GEN_ST_CHANNEL';

COMMENT ON COLUMN PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT.ITMINDS_DATA_IDENTIFIER IS 'Ins =  for Data Insertion of ITMINDS ,   Upd  =   for Data Update from ITMINDS.';


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_PART_ATL_ST CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_PART_ATL_ST
(
  S_NO               NUMBER,
  PARTICIPANT_ID_FK  NUMBER                     NOT NULL,
  START_DATE         DATE,
  END_DATE           DATE,
  ATL_STATUS         CHAR(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_TAX CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_TAX
(
  TAX_YEAR_ID_PK  NUMBER,
  TAX_YEAR        CHAR(4 BYTE),
  USER_ID_FK      NUMBER,
  ENTER_DATE      DATE                          DEFAULT SYSDATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_TAX_DTL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_TAX_DTL
(
  TAX_YEAR_ID_FK             NUMBER,
  S_NO                       NUMBER,
  START_DATE                 DATE,
  END_DATE                   DATE,
  USER_ID_FK                 NUMBER,
  ENTER_DATE                 DATE               DEFAULT SYSDATE,
  TAX_PERCENTAGE             NUMBER,
  TAX_PERCENTAGE_NON_EXEMPT  NUMBER,
  DIVIDENT_TAX               NUMBER,
  DIVIDENT_TAX_NON_EXEMPT    NUMBER,
  PARTICIPANT_TYPE           CHAR(1 BYTE),
  CGT_TAX_EXEMPT             NUMBER,
  CGT_TAX_NON_EXEMPT         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_TRNS_TYPE CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_TRNS_TYPE
(
  TRNS_TYPE_ID_PK  NUMBER,
  TRNS_TYPE        CHAR(1 BYTE),
  TRNS_DESC        VARCHAR2(100 BYTE),
  USER_ID_FK       NUMBER,
  ENTER_DATE       DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE
(
  UNIT_TYPE_ID_PK  NUMBER,
  UNIT_TYPE_NAME   VARCHAR2(50 BYTE),
  ENTER_DATE       DATE,
  USER_ID_FK       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE_DTL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE_DTL
(
  UNIT_TYPE_DT_PK  NUMBER,
  UNIT_TYPE_ID_FK  NUMBER,
  EFFECTIVE_DT     DATE,
  FM_AMOUNT        NUMBER,
  TO_AMOUNT        NUMBER,
  ENTER_DATE       DATE,
  USER_ID_FK       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_IMC_CALC_AMC CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_IMC_CALC_AMC
(
  PARTICIPANT_ID_FK  NUMBER,
  FUND_TYPE_ID_FK    NUMBER,
  PRICING_DATE       DATE,
  NO_UNITS           NUMBER,
  UNIT_PRICE         NUMBER,
  CASH_VALUE         NUMBER,
  IMC_AMOUNT         NUMBER,
  ENTER_DATE         DATE,
  AGENCY_ID_FK       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_KNOCKOFF_LEDGER CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_KNOCKOFF_LEDGER
(
  KNOCKOFF_LEDGER_ID_PK         NUMBER,
  OUT_TRANSACTION_LEDGER_ID_FK  NUMBER,
  SALE_AGENT_LEDGER_ID_FK       NUMBER,
  UNIT_OUT                      NUMBER,
  ENTER_DATE                    DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_KNOCKOFF_LEDGER_BACKUP CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_KNOCKOFF_LEDGER_BACKUP
(
  KNOCKOFF_LEDGER_ID_PK         NUMBER,
  OUT_TRANSACTION_LEDGER_ID_FK  NUMBER,
  SALE_AGENT_LEDGER_ID_FK       NUMBER,
  UNIT_OUT                      NUMBER,
  ENTER_DATE                    DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_NAV_RATE CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_NAV_RATE
(
  NAV_ID_PK        NUMBER                       NOT NULL,
  NAV_DATE         DATE,
  FUND_TYPE_ID_FK  NUMBER,
  NAV_RATE         NUMBER                       NOT NULL,
  ENTER_DATE       DATE                         NOT NULL,
  USER_ID_FK       NUMBER                       NOT NULL,
  NET_ASSETS       NUMBER,
  I_C              CHAR(1 BYTE)                 DEFAULT 'N',
  RATE             NUMBER,
  OFFER_RATES      NUMBER,
  BID_RATES        NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_SALE_AGENT_LEDGER CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_SALE_AGENT_LEDGER
(
  SALE_AGENT_LEDGER_ID_PK      NUMBER,
  IN_TRANSACTION_LEDGER_ID_FK  NUMBER,
  AGENT_ID_FK                  NUMBER,
  UNIT_IN                      NUMBER,
  ENTER_DATE                   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN PQAMCLUM.PQAMC_SALE_AGENT_LEDGER.IN_TRANSACTION_LEDGER_ID_FK IS 'pqamc_transaction_ledger.transaction_ledger_id_pk';


DROP TABLE PQAMCLUM.PQAMC_STAGE_UNITS_DTL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_STAGE_UNITS_DTL
(
  TEMP_ID             NUMBER,
  STAGE_CODE          VARCHAR2(100 BYTE),
  TRNS_DTL_ID_FK      NUMBER,
  REF_TRNS_DTL_ID_PK  NUMBER,
  TRANS_IN_TERM       VARCHAR2(50 BYTE),
  USER_ID_FK          NUMBER,
  ENTER_DATE          DATE,
  TRANSACTION_ID_FK   NUMBER,
  FUND_TYPE_ID_FK     NUMBER,
  UNIT_TYPE_ID_FK     NUMBER,
  CRITERIA_VALUE      VARCHAR2(200 BYTE),
  GROSS_AMOUNT        NUMBER,
  INVEST_AMOUNT       NUMBER,
  RATE                NUMBER,
  NAV_DATE            DATE,
  QUANTITY            NUMBER,
  TRNS_TYPE           VARCHAR2(50 BYTE),
  CREATED_BY          NUMBER,
  CREATED_ON          DATE                      DEFAULT SYSDATE,
  SALES_CREATED       CHAR(1 BYTE)              DEFAULT 'N'
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_TRANSACTION_LEDGER CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_TRANSACTION_LEDGER
(
  TRANSACTION_LEDGER_ID_PK  NUMBER,
  TRANSACTION_LEDGER_DATE   DATE,
  TRANSACTION_CODE          VARCHAR2(21 BYTE),
  TRANSACTION_TIME          DATE,
  PARTICIPANT_ID_FK         NUMBER,
  AGENT_ID_FK               NUMBER,
  REMARKS                   VARCHAR2(500 BYTE),
  COMPANY_ID_FK             NUMBER,
  INVOICE_NO                VARCHAR2(50 BYTE),
  VOUCHER_NO                VARCHAR2(50 BYTE),
  UNIT_IN                   NUMBER,
  UNIT_OUT                  NUMBER,
  TRANSACTION_ID_FK         NUMBER,
  TRANSACTION_DATE          DATE,
  TRNS_DTL_ID_FK            NUMBER,
  FUND_TYPE_ID_FK           NUMBER,
  UNIT_TYPE_ID_FK           NUMBER,
  NAV_VALUE                 NUMBER,
  NAV_DATE                  DATE,
  GROSS_AMOUNT              NUMBER,
  LOAD_PERCENTAGE           NUMBER,
  LOAD_AMOUNT               NUMBER,
  CGT_AMOUNT                NUMBER,
  TRANSACTION_FLAG          VARCHAR2(2 BYTE),
  TRANS_ENTER_USER_ID_FK    NUMBER,
  TRANS_ENTER_DATE          DATE,
  TRANS_POST_USER_ID_FK     NUMBER,
  TRANS_POST_DATE           DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_UNITS_LEDGER CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UNITS_LEDGER
(
  LEDGER_ID_PK       NUMBER,
  LEDGER_DATE        DATE,
  UNITS_IN           NUMBER,
  UNITS_OUT          NUMBER,
  TRANSACTION_ID_PK  NUMBER,
  TRANS_FLAG         CHAR(1 BYTE),
  TRNS_DTL_ID_PK     NUMBER,
  NAV_DATE           DATE,
  FUND_TYPE_ID_FK    NUMBER,
  GROSS_AMOUNT       NUMBER,
  CHARGES            NUMBER,
  CHARGES_AMT        NUMBER,
  TAX_PCT            NUMBER,
  TAX_AMOUNT         NUMBER,
  NET_AMOUNT         NUMBER,
  CGT_PER            NUMBER,
  CGT_AMOUNT         NUMBER,
  TRANSACTION_DATE   DATE,
  ENTER_DATE         DATE,
  USER_ID_FK         NUMBER,
  PARTICIPANT_ID_FK  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION
(
  TRANSACTION_ID_PK    NUMBER                   NOT NULL,
  TRANSACTION_CODE     VARCHAR2(21 BYTE),
  TRANSACTION_DATE     DATE,
  TRANSACTION_TIME     DATE,
  NAV_DATE             DATE,
  AGENT_ID_FK          NUMBER,
  PARTICIPANT_ID_FK    NUMBER,
  FUND_TYPE_ID_FK      NUMBER,
  QUANTITY             NUMBER,
  RATE                 NUMBER,
  GROSS_AMOUNT         NUMBER,
  CHARGES              NUMBER,
  INVEST_AMOUNT        NUMBER,
  USER_ID_FK           NUMBER,
  ENTER_DATE           DATE,
  POST_USER_ID_FK      NUMBER,
  POST_DATE            DATE,
  CANCEL_USER_ID_FK    NUMBER,
  CANCEL_DATE          DATE,
  REMARKS              VARCHAR2(500 BYTE),
  INVOICE_NO           VARCHAR2(50 BYTE),
  VOUCHER_NO           VARCHAR2(100 BYTE),
  COMPANY_ID_FK        NUMBER,
  TRANS_FLAG           CHAR(1 BYTE),
  TRANS_IN_TERM        NUMBER,
  UNIT_TYPE_ID_FK      NUMBER,
  NAV_PROCESS          DATE,
  CONVERSION_CRITERIA  CHAR(1 BYTE),
  CANCEL_YN            CHAR(1 BYTE)             DEFAULT 'N',
  PERIOD_FROM          DATE,
  PERIOD_TO            DATE,
  ALTERATION_FLAG      CHAR(1 BYTE)             DEFAULT 'N',
  APPROVE_USER_ID_FK   NUMBER,
  AGE_ROUNDING         NUMBER,
  PARTICIPANT_TYPE     CHAR(1 BYTE),
  APPROVE_DATE         DATE,
  COMPANYID_FK         NUMBER,
  ADD_REMARK           VARCHAR2(500 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN PQAMCLUM.PQAMC_UNITS_TRANSACTION.TRANS_IN_TERM IS '1=All Units,2=Units,3=Amount';


DROP TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL
(
  TRNS_DTL_ID_PK      NUMBER,
  TRANSACTION_ID_FK   NUMBER,
  FUND_TYPE_ID_FK     NUMBER,
  UNIT_TYPE_ID_FK     NUMBER,
  TRANS_IN_TERM       NUMBER,
  QUANTITY            NUMBER,
  RATE                NUMBER,
  GROSS_AMOUNT        NUMBER,
  CHARGES             NUMBER,
  TAX_PCT             NUMBER,
  INVEST_AMOUNT       NUMBER,
  USER_ID_FK          NUMBER,
  ENTER_DATE          DATE,
  NAV_DATE            DATE,
  ORIGINAL_TAX_PCT    NUMBER,
  ORIGINAL_CHARGES    NUMBER,
  TRNS_TYPE           CHAR(1 BYTE),
  REF_TRNS_DTL_ID_PK  NUMBER,
  CRITERIA_VALUE      NUMBER,
  IS_EXECUTED         VARCHAR2(1 BYTE),
  EXECUTION_DATE      DATE,
  TAX_AMOUNT          NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;

COMMENT ON COLUMN PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL.TRANS_IN_TERM IS '1=All Units,2=Units,3=Amount';

COMMENT ON COLUMN PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL.TRNS_TYPE IS 'Reference Table = PQAMC_GEN_ST_TRNS_TYPE';

COMMENT ON COLUMN PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL.REF_TRNS_DTL_ID_PK IS 'Reference ID for Conversion Transaction';


DROP TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION_PYMT CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION_PYMT
(
  PYMT_ID_PK            NUMBER,
  TRANSACTION_ID_PK     NUMBER,
  INSTRUMENT_TYPE       NUMBER,
  INSTRUMENT_NO         VARCHAR2(100 BYTE),
  BANK_ID_FK            NUMBER,
  BANK_BR_ID_FK         NUMBER,
  USER_ID_FK            NUMBER,
  ENTER_DATE            DATE,
  INSTRUMENT_DATE       DATE,
  CLIENT_BANK_ID_FK     NUMBER,
  CLIENT_BANK_BR_ID_FK  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_UW_ALTERATION_DETAIL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UW_ALTERATION_DETAIL
(
  ALTERATION_DTL_ID_PK         NUMBER           NOT NULL,
  ALTERATION_ID_FK             NUMBER,
  TRANSACTION_ID_FK            NUMBER,
  EMPLOYEE_ID_FK               NUMBER,
  CERTIFICATE_NO               VARCHAR2(150 BYTE),
  EMP_TITLE                    VARCHAR2(30 BYTE),
  EMP_TITLE_OLD                VARCHAR2(30 BYTE),
  EMPLOYEE_NAME                VARCHAR2(1500 BYTE),
  EMPLOYEE_NAME_OLD            VARCHAR2(1500 BYTE),
  EMPLOYEE_CODE                VARCHAR2(120 BYTE),
  EMPLOYEE_CODE_OLD            VARCHAR2(120 BYTE),
  CNIC_NO                      VARCHAR2(150 BYTE),
  CNIC_NO_OLD                  VARCHAR2(150 BYTE),
  DOB                          DATE,
  DOB_OLD                      DATE,
  AGE                          NUMBER,
  AGE_OLD                      NUMBER,
  GENDER                       VARCHAR2(3 BYTE),
  GENDER_OLD                   VARCHAR2(3 BYTE),
  MARITAL_STATUS               VARCHAR2(3 BYTE),
  MARITAL_STATUS_OLD           VARCHAR2(3 BYTE),
  EFFECTIVE_DT                 DATE,
  EFFECTIVE_DT_OLD             DATE,
  EMAIL_ADDRESS                VARCHAR2(450 BYTE),
  EMAIL_ADDRESS_OLD            VARCHAR2(450 BYTE),
  MOBILE_NO                    VARCHAR2(60 BYTE),
  MOBILE_NO_OLD                VARCHAR2(60 BYTE),
  ACCOUNT_NO                   VARCHAR2(120 BYTE),
  ACCOUNT_NO_OLD               VARCHAR2(120 BYTE),
  BANK_CODE                    VARCHAR2(120 BYTE),
  BANK_CODE_OLD                VARCHAR2(120 BYTE),
  FATHER_NAME                  VARCHAR2(1500 BYTE),
  FATHER_NAME_OLD              VARCHAR2(1500 BYTE),
  FATHER_CNIC                  VARCHAR2(150 BYTE),
  FATHER_CNIC_OLD              VARCHAR2(150 BYTE),
  MOTHER_NAME                  VARCHAR2(1500 BYTE),
  MOTHER_NAME_OLD              VARCHAR2(1500 BYTE),
  MOTHER_CNIC                  VARCHAR2(150 BYTE),
  MOTHER_CNIC_OLD              VARCHAR2(150 BYTE),
  SUM_COVERED                  NUMBER,
  SUM_COVERED_OLD              NUMBER,
  BENEFITS_PAYMENT_ID_FK       NUMBER,
  BENEFITS_PAYMENT_ID_FK_OLD   NUMBER,
  ALTERATION_EFFECTIVE_DT      DATE,
  FUND_TYPE_ID_FK_FROM         NUMBER,
  FUND_TYPE_ID_FK_TO           NUMBER,
  CONVERSION_PCT               NUMBER,
  CONVERSION_AMOUNT            NUMBER,
  ZAKAT_DECLARATION            VARCHAR2(3 BYTE),
  ATL_STATUS                   VARCHAR2(3 BYTE),
  ZAKAT_DECLARATION_OLD        VARCHAR2(3 BYTE),
  ATL_STATUS_OLD               VARCHAR2(3 BYTE),
  EMP_DESIGNATION              VARCHAR2(1050 BYTE),
  EMP_DESIGNATION_OLD          VARCHAR2(1050 BYTE),
  RELIGION_ID_FK               NUMBER,
  RELIGION_ID_FK_OLD           NUMBER,
  SMOKER_FLAG                  VARCHAR2(3 BYTE),
  SMOKER_FLAG_OLD              VARCHAR2(3 BYTE),
  FUND_TYPE_ID_FK              NUMBER,
  FUND_TYPE_ID_FK_OLD          NUMBER,
  EMP_ADDRESS                  VARCHAR2(1500 BYTE),
  EMP_ADDRESS_OLD              VARCHAR2(1500 BYTE),
  OCCUPATION_ID_FK             NUMBER,
  OCCUPATION_ID_FK_OLD         NUMBER,
  CITY_ID_FK                   NUMBER,
  CITY_ID_FK_OLD               NUMBER,
  UW_STATUS_ID_FK              NUMBER,
  UW_STATUS_ID_FK_OLD          NUMBER,
  CONTRIBUTION                 NUMBER,
  CONTRIBUTION_OLD             NUMBER,
  EMP_CATEGORY_ID_FK           NUMBER,
  EMP_CATEGORY_ID_FK_OLD       NUMBER,
  CRITERIA                     VARCHAR2(3 BYTE),
  MODE_OF_PAYMENT_ID           NUMBER,
  MODE_OF_PAYMENT_ID_OLD       NUMBER,
  RESIDENTIAL_STATUS           CHAR(3 BYTE),
  RESIDENTIAL_STATUS_OLD       CHAR(3 BYTE),
  PROFIT_TYPE                  NUMBER,
  PROFIT_TYPE_OLD              NUMBER,
  PROFIT_FIXED_AMT             NUMBER,
  PROFIT_FIXED_AMT_OLD         NUMBER,
  STOP_EPMD                    CHAR(3 BYTE),
  STOP_EPMD_OLD                CHAR(3 BYTE),
  EMP_ADDRESS_2                VARCHAR2(450 BYTE),
  EMP_ADDRESS_2_OLD            VARCHAR2(450 BYTE),
  EMP_ADDRESS_3                VARCHAR2(450 BYTE),
  EMP_ADDRESS_3_OLD            VARCHAR2(450 BYTE),
  ALT_MOBILE_NO                VARCHAR2(60 BYTE),
  ALT_MOBILE_NO_OLD            VARCHAR2(60 BYTE),
  IBAN_NO                      VARCHAR2(120 BYTE),
  IBAN_NO_OLD                  VARCHAR2(120 BYTE),
  BANK_ID_FK                   NUMBER,
  BANK_ID_FK_OLD               NUMBER,
  SUBSIDIARY_COMPANY           VARCHAR2(300 BYTE),
  SUBSIDIARY_COMPANY_OLD       VARCHAR2(300 BYTE),
  COUNTRY_ID_FK                NUMBER,
  COUNTRY_ID_FK_OLD            NUMBER,
  EMP_STATUS_ID_FK             NUMBER,
  EMP_STATUS_ID_FK_OLD         NUMBER,
  EPMD                         CHAR(3 BYTE),
  EPMD_OLD                     CHAR(3 BYTE),
  RESIDENT_COUNTRY_ID_FK       NUMBER,
  RESIDENT_COUNTRY_ID_FK_OLD   NUMBER,
  PARENT_PARTICIPANT_ID_FK     NUMBER,
  PROPOSER_RELATION_ID         NUMBER,
  CNIC_EXPIRY_DATE             DATE,
  FATHER_CNIC_EXPIRY_DATE      DATE,
  MOTHER_CNIC_EXPIRY_DATE      DATE,
  ZAKAT_MANUAL_DEC             VARCHAR2(3 BYTE),
  ZAKAT_MANUAL_DEC_OLD         VARCHAR2(3 BYTE),
  IBAN_VERIFY_FLAG             VARCHAR2(3 BYTE),
  IBAN_VERIFY_FLAG_OLD         VARCHAR2(3 BYTE),
  IBAN_MANUAL_VERIFY_FLAG      VARCHAR2(3 BYTE),
  IBAN_MANUAL_VERIFY_FLAG_OLD  VARCHAR2(3 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_UW_ALTERATION_MASTER CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UW_ALTERATION_MASTER
(
  ALTERATION_ID_PK       NUMBER                 NOT NULL,
  ALTERATION_CODE        VARCHAR2(90 BYTE),
  TRANSACTION_ID_FK      NUMBER,
  ALTERATION_DATE        DATE                   NOT NULL,
  ALTERATION_TYPE_ID_FK  NUMBER                 NOT NULL,
  REMARKS                VARCHAR2(1800 BYTE),
  USER_ID_FK             NUMBER                 NOT NULL,
  ENTER_DATE             DATE,
  POST_USER_ID_FK        NUMBER,
  POST_DATE              DATE,
  ALTERATION_TYPE        NUMBER,
  CANCEL_DATE            DATE,
  CANCEL_USER_ID_FK      NUMBER,
  COMPANYID_FK           NUMBER,
  EMAIL                  CHAR(3 BYTE),
  FUND_SELLING_ID_PK     NUMBER,
  FUND_CONVERSION_ID_FK  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_UW_EMP_CATEGORY_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UW_EMP_CATEGORY_HISTORY
(
  EMP_CATEGORY_ID_PK  NUMBER,
  DOCUMENT_ID_FK      NUMBER,
  CATG_CODE           VARCHAR2(30 BYTE),
  CATG_DESC           VARCHAR2(150 BYTE),
  ALLOCATION_CHARGES  NUMBER,
  TAKAFUL_CHARGES     NUMBER,
  ADMIN_CHARGES       NUMBER,
  BACKEND_LOAD        NUMBER,
  USER_ID_FK          NUMBER,
  ENTER_DATE          DATE,
  WITHDRAW_LIMIT      NUMBER,
  MORTALITY_CHG       VARCHAR2(3 BYTE),
  ALTERATION_ID_FK    NUMBER,
  DUMMY               VARCHAR2(300 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_UW_NOMINEES CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UW_NOMINEES
(
  NOM_ID_PK           NUMBER,
  TRANSACTION_ID_FK   NUMBER,
  EMPLOYEE_ID_FK      NUMBER,
  NOM_NAME            VARCHAR2(300 BYTE),
  NOM_DOB             DATE,
  NOM_CNIC            VARCHAR2(90 BYTE),
  NOM_CNIC_ISS_DT     DATE,
  NOM_CNIC_EXP_DT     DATE,
  NOM_SHARE           NUMBER,
  NOM_EFFECTIVE_DT    DATE,
  NOM_STATUS          CHAR(3 BYTE),
  NOM_REL_ID_FK       NUMBER,
  ENTER_DATE          DATE,
  USER_ID_FK          NUMBER,
  ALTERATION_ID_FK    NUMBER,
  GUARDIAN_CNIC       VARCHAR2(90 BYTE),
  GUARDIAN_NAME       VARCHAR2(300 BYTE),
  GUARDIAN_REL_ID_FK  NUMBER,
  ENTER_DATE_BKUP     DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_UW_NOMINEES_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UW_NOMINEES_HISTORY
(
  NOM_ID_FK                NUMBER,
  TRANSACTION_ID_FK        NUMBER,
  EMPLOYEE_ID_FK           NUMBER,
  NOM_NAME                 VARCHAR2(300 BYTE),
  NOM_DOB                  DATE,
  NOM_CNIC                 VARCHAR2(90 BYTE),
  NOM_CNIC_ISS_DT          DATE,
  NOM_CNIC_EXP_DT          DATE,
  NOM_SHARE                NUMBER,
  NOM_EFFECTIVE_DT         DATE,
  NOM_STATUS               CHAR(3 BYTE),
  NOM_REL_ID_FK            NUMBER,
  ALTERATION_ID_FK         NUMBER,
  DUMMY                    VARCHAR2(150 BYTE),
  ENTER_DATE               DATE,
  USER_ID_FK               NUMBER,
  ALTERATION_PROCESS_DATE  DATE,
  GUARDIAN_CNIC            VARCHAR2(90 BYTE),
  GUARDIAN_NAME            VARCHAR2(300 BYTE),
  GUARDIAN_REL_ID_FK       NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.PQAMC_UW_POLICY_ASSIGNEE_DTL CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.PQAMC_UW_POLICY_ASSIGNEE_DTL
(
  ASSIGNEE_ID_PK     NUMBER                     NOT NULL,
  TRANSACTION_ID_FK  NUMBER,
  EMPLOYEE_ID_FK     NUMBER,
  PARTICIPANT_ID_FK  NUMBER,
  ASSIGN_TYPE_ID_FK  NUMBER,
  START_DATE         DATE,
  END_DATE           DATE,
  REMARKS            VARCHAR2(4000 BYTE),
  ASSIGNEEE_STATUS   VARCHAR2(3 BYTE),
  USER_ID_FK         VARCHAR2(600 BYTE),
  ENTER_DATE         DATE,
  LAST_USER_ID       VARCHAR2(600 BYTE),
  LAST_UPDATED_DATE  DATE,
  ASSIGN_REF_ID      NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.VU_AGENT_PQAMC_PRODUCTION_2023 CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.VU_AGENT_PQAMC_PRODUCTION_2023
(
  SUBMISSION_DATE     DATE,
  ISSUANCE_DATE       DATE,
  DOCUMENT_ID_PK      NUMBER,
  DOCUMENT_CODE       VARCHAR2(35 BYTE),
  EMPLOYEE_ID_PK      NUMBER                    NOT NULL,
  PARTICIPANT_TYPE    CHAR(1 BYTE),
  PLAN_ID_FK          NUMBER,
  CONTRIBUTION        NUMBER,
  AGENCY_ID_FK        NUMBER,
  V_RANK_CODE         VARCHAR2(20 BYTE),
  CURRENT_RANK        VARCHAR2(20 BYTE),
  COMMISSION_RATE     NUMBER,
  COMMISSION_AMOUNT   NUMBER,
  PROD_PCT            NUMBER,
  TRANSACTION_ID_PK   NUMBER,
  TRNS_TYPE           VARCHAR2(1 BYTE),
  TRANSACTION_AMOUNT  NUMBER,
  BIZ_CREDIT          NUMBER,
  SUB_CREDIT          NUMBER,
  CONTRI_STATUS       VARCHAR2(8 BYTE),
  PARTICIPANT_NAME    VARCHAR2(500 BYTE),
  AGENT_CODE          VARCHAR2(30 BYTE),
  AGENT_NAME          VARCHAR2(400 BYTE),
  POLICY_YEAR         CHAR(1 BYTE),
  CERTIFICATE_NO      VARCHAR2(50 BYTE),
  EMPLOYEE_NAME       VARCHAR2(350 BYTE),
  PLAN_NAME           VARCHAR2(150 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


DROP TABLE PQAMCLUM.VU_PQAMC_PRODUCTION_TEMP CASCADE CONSTRAINTS;

CREATE TABLE PQAMCLUM.VU_PQAMC_PRODUCTION_TEMP
(
  SUBMISSION_DATE     DATE,
  ISSUANCE_DATE       DATE,
  DOCUMENT_ID_PK      NUMBER,
  DOCUMENT_CODE       VARCHAR2(35 BYTE),
  EMPLOYEE_ID_PK      NUMBER                    NOT NULL,
  PLAN_ID_FK          NUMBER,
  CONTRIBUTION        NUMBER,
  AGENCY_ID_FK        NUMBER,
  V_RANK_CODE         VARCHAR2(20 BYTE),
  CURRENT_RANK        VARCHAR2(20 BYTE),
  COMMISSION_RATE     NUMBER,
  PROD_PCT            NUMBER,
  TRANSACTION_ID_PKK  NUMBER,
  TRNS_TYPE           VARCHAR2(1 BYTE),
  TRANSACTION_AMOUNT  NUMBER,
  BIZ_CREDIT          NUMBER,
  SUB_CREDIT          NUMBER,
  CONTRI_STATUS       CHAR(7 BYTE),
  PARTICIPANT_NAME    VARCHAR2(500 BYTE),
  AGENT_CODE          VARCHAR2(30 BYTE),
  AGENT_NAME          VARCHAR2(400 BYTE),
  POLICY_YEAR         CHAR(1 BYTE),
  CERTIFICATE_NO      VARCHAR2(50 BYTE),
  EMPLOYEE_NAME       VARCHAR2(350 BYTE),
  CNIC_NO             VARCHAR2(20 BYTE),
  PLAN_NAME           VARCHAR2(150 BYTE),
  COMMISSION_AMOUNT   NUMBER,
  TRANSACTION_DATE    DATE,
  PARTICIPANT_TYPE    CHAR(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX PQAMCLUM.BENEFICIARY_ID_PK ON PQAMCLUM.PQAMC_GEN_PART_BENEFICIARY
(BENEFICIARY_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.BEN_PART_INDX ON PQAMCLUM.PQAMC_GEN_PART_BENEFICIARY
(PARTICIPANT_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.CHAGES_COMP_PK ON PQAMCLUM.PQAMC_GEN_ST_CHARGES_TAX
(FUND_TYPE_ID_FK, EFFECTIVE_DT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.CHAGES_ID_PK ON PQAMCLUM.PQAMC_GEN_ST_CHARGES_TAX
(CHAGES_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.CHRG_FUND_INDX ON PQAMCLUM.PQAMC_GEN_ST_CHARGES_TAX
(FUND_TYPE_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.COMP_PK ON PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE_DTL
(FUND_TYPE_ID_FK, UNIT_TYPE_ID_FK, FM_AMOUNT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.COMP_UNITS_INDX ON PQAMCLUM.PQAMC_UNITS_TRANSACTION
(PARTICIPANT_ID_FK, FUND_TYPE_ID_FK, TRANSACTION_DATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.FUND_DTL_ID_PK ON PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE_DTL
(FUND_DTL_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.FUND_NAME_UQ ON PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE
(FUND_TYPE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.NAME_UNIQ ON PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE
(UNIT_TYPE_NAME)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.NAV_COMP_PK ON PQAMCLUM.PQAMC_NAV_RATE
(NAV_DATE, FUND_TYPE_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.NAV_DATE_IND ON PQAMCLUM.PQAMC_NAV_RATE
(NAV_DATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.NAV_FUND_INXD ON PQAMCLUM.PQAMC_NAV_RATE
(FUND_TYPE_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.NAV_ID_PK_UQ ON PQAMCLUM.PQAMC_NAV_RATE
(NAV_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.PARTICIPANT_ID_FK_INDX ON PQAMCLUM.PQAMC_UNITS_TRANSACTION
(PARTICIPANT_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.PGPTD ON PQAMCLUM.PQAMC_GEN_PART_TAX_DTL
(TAX_MST_FK, S_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.PGPTM ON PQAMCLUM.PQAMC_GEN_PART_TAX_MST
(TAX_MST_ID, PARTICIPANT_ID_FK, SETUP_DTL_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.PK_PQAMC_SALE_AGENT_LEDGER ON PQAMCLUM.PQAMC_SALE_AGENT_LEDGER
(SALE_AGENT_LEDGER_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.PQAMC_FUND_ID ON PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE
(FUND_TYPE_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.PQAMC_IMC_COM_PKID ON PQAMCLUM.PQAMC_GEN_ST_IMC_RATE
(FUND_TYPE_ID_FK, EFF_FROM_DT, EFF_TO_DT)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.PQAMC_PARTICIPANT_ID_PK ON PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT
(PARTICIPANT_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.PQAMC_RATE_ID_PK ON PQAMCLUM.PQAMC_GEN_ST_IMC_RATE
(RATE_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.PYMT_BANK_IND ON PQAMCLUM.PQAMC_UNITS_TRANSACTION_PYMT
(BANK_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.PYMT_BRANCH_IND ON PQAMCLUM.PQAMC_UNITS_TRANSACTION_PYMT
(BANK_BR_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.PYMT_ID_PK ON PQAMCLUM.PQAMC_UNITS_TRANSACTION_PYMT
(PYMT_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

--  There is no statement for index PQAMCLUM.SYS_C00331388.
--  The object is created when the parent object is created.

--  There is no statement for index PQAMCLUM.SYS_C00331472.
--  The object is created when the parent object is created.

--  There is no statement for index PQAMCLUM.SYS_C00331940.
--  The object is created when the parent object is created.

--  There is no statement for index PQAMCLUM.SYS_C00331945.
--  The object is created when the parent object is created.

--  There is no statement for index PQAMCLUM.SYS_C00331946.
--  The object is created when the parent object is created.

--  There is no statement for index PQAMCLUM.SYS_C00333109.
--  The object is created when the parent object is created.

--  There is no statement for index PQAMCLUM.SYS_C00333198.
--  The object is created when the parent object is created.

--  There is no statement for index PQAMCLUM.SYS_C00334819.
--  The object is created when the parent object is created.

CREATE UNIQUE INDEX PQAMCLUM.TRANSACTION_CODE_UK_UNITS ON PQAMCLUM.PQAMC_UNITS_TRANSACTION
(TRANSACTION_CODE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.TRANSACTION_PK_UNITS ON PQAMCLUM.PQAMC_UNITS_TRANSACTION
(TRANSACTION_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.TRNS_DTL_COMP_PK ON PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL
(TRANSACTION_ID_FK, FUND_TYPE_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.TRNS_DTL_ID_PK ON PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL
(TRNS_DTL_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.TRNS_FUND_DTL_INDX ON PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL
(FUND_TYPE_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.TRNS_ID_DTL_INDX ON PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL
(TRANSACTION_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.UNITS_FUND_TYPE_ID_FK ON PQAMCLUM.PQAMC_UNITS_TRANSACTION
(FUND_TYPE_ID_FK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE INDEX PQAMCLUM.UNITS_TRANS_DT_INDX ON PQAMCLUM.PQAMC_UNITS_TRANSACTION
(TRANSACTION_DATE)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.UNIT_TYPE_DT_PK ON PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE_DTL
(UNIT_TYPE_DT_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

CREATE UNIQUE INDEX PQAMCLUM.UNIT_TYPE_ID_PK ON PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE
(UNIT_TYPE_ID_PK)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE PQAMCLUM.PQAMC_DIVIDEND_PROCESS_DETAIL ADD (
  PRIMARY KEY
  (PROCESS_DETAIL_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_DIVIDEND_PROCESS_MASTER ADD (
  PRIMARY KEY
  (PROCESS_ID_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_FIFO_TRACK ADD (
  PRIMARY KEY
  (TRACK_ID)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_FOLIO_TRANSFER_LOG ADD (
  PRIMARY KEY
  (FOLIO_TRANSFER_ID_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_PART_BENEFICIARY ADD (
  CONSTRAINT BENEFICIARY_ID_PK
  PRIMARY KEY
  (BENEFICIARY_ID_PK)
  USING INDEX PQAMCLUM.BENEFICIARY_ID_PK
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_PART_DIRECTORS ADD (
  PRIMARY KEY
  (DIRECTOR_ID_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_PART_SIGNATORY ADD (
  PRIMARY KEY
  (SIGNATORY_ID_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_PART_TAX_DTL ADD (
  CONSTRAINT PGPTD
  PRIMARY KEY
  (TAX_MST_FK, S_NO)
  USING INDEX PQAMCLUM.PGPTD
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_PART_TAX_MST ADD (
  CONSTRAINT PGPTM
  PRIMARY KEY
  (TAX_MST_ID, PARTICIPANT_ID_FK, SETUP_DTL_ID_FK)
  USING INDEX PQAMCLUM.PGPTM
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_CHARGES_TAX ADD (
  CONSTRAINT CHAGES_ID_PK
  PRIMARY KEY
  (CHAGES_ID_PK)
  USING INDEX PQAMCLUM.CHAGES_ID_PK
  ENABLE VALIDATE
,  CONSTRAINT CHAGES_COMP_PK
  UNIQUE (FUND_TYPE_ID_FK, EFFECTIVE_DT)
  USING INDEX PQAMCLUM.CHAGES_COMP_PK
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_FUND ADD (
  PRIMARY KEY
  (FUND_ID_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE ADD (
  CONSTRAINT PQAMC_FUND_ID
  PRIMARY KEY
  (FUND_TYPE_ID_PK)
  USING INDEX PQAMCLUM.PQAMC_FUND_ID
  ENABLE VALIDATE
,  CONSTRAINT FUND_NAME_UQ
  UNIQUE (FUND_TYPE_NAME)
  USING INDEX PQAMCLUM.FUND_NAME_UQ
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_FUND_TYPE_DTL ADD (
  CONSTRAINT FUND_DTL_ID_PK
  PRIMARY KEY
  (FUND_DTL_ID_PK)
  USING INDEX PQAMCLUM.FUND_DTL_ID_PK
  ENABLE VALIDATE
,  CONSTRAINT COMP_PK
  UNIQUE (FUND_TYPE_ID_FK, UNIT_TYPE_ID_FK, FM_AMOUNT)
  USING INDEX PQAMCLUM.COMP_PK
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_IMC_RATE ADD (
  CONSTRAINT PQAMC_RATE_ID_PK
  PRIMARY KEY
  (RATE_ID_PK)
  USING INDEX PQAMCLUM.PQAMC_RATE_ID_PK
  ENABLE VALIDATE
,  CONSTRAINT PQAMC_IMC_COM_PKID
  UNIQUE (FUND_TYPE_ID_FK, EFF_FROM_DT, EFF_TO_DT)
  USING INDEX PQAMCLUM.PQAMC_IMC_COM_PKID
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_MANAGEMENT_CHARGE ADD (
  PRIMARY KEY
  (MANAGEMENT_ID_PK)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_PARTICIPANT ADD (
  CONSTRAINT PQAMC_PARTICIPANT_ID_PK
  PRIMARY KEY
  (PARTICIPANT_ID_PK)
  USING INDEX PQAMCLUM.PQAMC_PARTICIPANT_ID_PK
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE ADD (
  CONSTRAINT UNIT_TYPE_ID_PK
  PRIMARY KEY
  (UNIT_TYPE_ID_PK)
  USING INDEX PQAMCLUM.UNIT_TYPE_ID_PK
  ENABLE VALIDATE
,  CONSTRAINT NAME_UNIQ
  UNIQUE (UNIT_TYPE_NAME)
  USING INDEX PQAMCLUM.NAME_UNIQ
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_GEN_ST_UNIT_TYPE_DTL ADD (
  CONSTRAINT UNIT_TYPE_DT_PK
  PRIMARY KEY
  (UNIT_TYPE_DT_PK)
  USING INDEX PQAMCLUM.UNIT_TYPE_DT_PK
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_NAV_RATE ADD (
  CONSTRAINT NAV_COMP_PK
  PRIMARY KEY
  (NAV_DATE, FUND_TYPE_ID_FK)
  USING INDEX PQAMCLUM.NAV_COMP_PK
  ENABLE VALIDATE
,  CONSTRAINT NAV_ID_PK_UQ
  UNIQUE (NAV_ID_PK)
  USING INDEX PQAMCLUM.NAV_ID_PK_UQ
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_SALE_AGENT_LEDGER ADD (
  CONSTRAINT PK_PQAMC_SALE_AGENT_LEDGER
  PRIMARY KEY
  (SALE_AGENT_LEDGER_ID_PK)
  USING INDEX PQAMCLUM.PK_PQAMC_SALE_AGENT_LEDGER
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION ADD (
  CONSTRAINT TRANSACTION_PK_UNITS
  PRIMARY KEY
  (TRANSACTION_ID_PK)
  USING INDEX PQAMCLUM.TRANSACTION_PK_UNITS
  ENABLE VALIDATE
,  CONSTRAINT TRANSACTION_CODE_UK_UNITS
  UNIQUE (TRANSACTION_CODE)
  USING INDEX PQAMCLUM.TRANSACTION_CODE_UK_UNITS
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION_DTL ADD (
  CONSTRAINT TRNS_DTL_ID_PK
  PRIMARY KEY
  (TRNS_DTL_ID_PK)
  USING INDEX PQAMCLUM.TRNS_DTL_ID_PK
  ENABLE VALIDATE
,  CONSTRAINT TRNS_DTL_COMP_PK
  UNIQUE (TRANSACTION_ID_FK, FUND_TYPE_ID_FK)
  USING INDEX PQAMCLUM.TRNS_DTL_COMP_PK
  ENABLE VALIDATE);

ALTER TABLE PQAMCLUM.PQAMC_UNITS_TRANSACTION_PYMT ADD (
  CONSTRAINT PYMT_ID_PK
  PRIMARY KEY
  (PYMT_ID_PK)
  USING INDEX PQAMCLUM.PYMT_ID_PK
  ENABLE VALIDATE);
